<?php

namespace CmsBundle\Repository\Article;

use CmsBundle\Entity\Article\Item;
/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $url
     *
     * @return Item
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findItem($url)
    {
        // pokusime se najit kategorii
        $path = explode('/', $url);

        // vezmeme posleni cast cesty
        $itemSlug = array_pop($path);

        $categorySlug = array_pop($path);

        $qb = $this->createQueryBuilder('i')
                 ->join('i.category', 'c')
                 ->where('i.slug = ?1')
                 ->andWhere('c.slug = ?2')
                 ->setParameter(1, $itemSlug)
                 ->setParameter(2, $categorySlug);

        if (count($path))
        {
            $qb->andWhere('c.parentUrl = ?3')
                ->setParameter(3, join('/', $path));
        }

        return $qb->getQuery()->getOneOrNullResult();
    }
}
