<?php

namespace CmsBundle\Repository\Article;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{

    public function getByCategoryAndTags($category, $tags)
    {
        /*$this->createQueryBuilder('i')
             ->join('i.tags', 't')
             ->where('i.category = ?1')
             ->andWHere('');*/
    }

}
