services:
#    cms.example:
#        class: CmsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]



     cms.manager.widget:
        class: CmsBundle\Service\WidgetManager
        arguments:    ['@doctrine.orm.entity_manager', '@service_container']


     cms.widget.editor:
        class:        CmsBundle\Service\Widget\Editor
        arguments:    ['@doctrine.orm.entity_manager', '@form.factory']
        tags:
            -  { name: cms.widget }

     app.twig.cms:
        class: CmsBundle\Twig\CmsExtension
        arguments:    ['@doctrine.orm.entity_manager', '@cms.manager.widget']
        public: false
        tags:
           - { name: twig.extension }