<?php

namespace CmsBundle\Repository;

/**
 * DocumentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
