<?php

namespace CmsBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;


/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends NestedTreeRepository
{
    public function getNodesHierarchyQueryBuilder($node = null, $direct = false, array $options = array(), $includeNode = false)
    {
        $qb = parent::getNodesHierarchyQueryBuilder($node, $direct, $options, $includeNode);

        $qb->join('node.category', 'c');

        $qb->addSelect('c');

        return $qb;
    }
}
