<?php

namespace CmsBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;


/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends NestedTreeRepository
{
}
