<?php

namespace CmsBundle\Repository;

/**
 * WidgetImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetImageRepository extends \Doctrine\ORM\EntityRepository
{
}
